// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkfviuzyisszdxsyxanu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrZnZpdXp5aXNzemR4c3l4YW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMTgwNTMsImV4cCI6MjA2MjU5NDA1M30.u8S4JerG75qrhN9umptgJcMM3xXLu16CUNg4IUj_eRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);